on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get package version of self
        id: get_package_version
        uses: ./
        with:
          path: ./package.json

      - name: Print package version
        run: echo "Package version is ${{ steps.get_package_version.outputs.version }}"